name: cd

on:
  push:
    branches:
      - master
      - develop

env: 
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: "AKIAYU4G6MZI2J2XF6MH"
        aws-secret-access-key: "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"
        aws-region: ${{ env.AWS_REGION }}

    - name: Define variables
      run: |
        export AWS_ACCESS_KEY_ID=AKIAYU4G6MZI2J2XF6MH
        export AWS_SECRET_ACCESS_KEY=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
        
    - name: Publish on prod
      if: github.ref == 'refs/heads/master'
      run: ./publish.sh prod

    - name: Publish on dev
      if: github.ref == 'refs/heads/develop'
      run: ./publish.sh dev
